name: 'spotify_analytics'
version: '1.0.0'
config-version: 2

profile: 'spotify_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  spotify_analytics:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: analytics
    
vars:
  start_date: '2024-01-01'
  
tests:
  +store_failures: true
  +severity: warn
